version=0.1
[default.global.parameters]
stack_name = "ttec-demo-stack"


[default.build.parameters]
no_beta_features = true

[default.deploy.parameters]
region = "us-east-1"
capabilities = "CAPABILITY_NAMED_IAM"
confirm_changeset = true