version=0.1

[default.global.parameters]
parameter_overrides = "ParameterKey=Env,ParameterValue=local ParameterKey=EnvRegion,ParameterValue=localhost ParameterKey=DynamoDBHost,ParameterValue=http://172.18.0.2:8000 ParameterKey=DynamoDBTable,ParameterValue=customer-vanity-numbers-v2 ParameterKey=VanityLimit,ParameterValue=5"

[default.build.parameters]
no_beta_features = true

[default.deploy.parameters]
stack_name = "ttec-react-stack"
region = "us-east-1"
s3_bucket = "ttec-deployment-artifacts"
s3_prefix = "react-app"
capabilities = "CAPABILITY_NAMED_IAM"
confirm_changeset = true

[dev.global.parameters]
parameter_overrides = "ParameterKey=Env,ParameterValue=development ParameterKey=EnvRegion,ParameterValue=us-east-1 ParameterKey=DynamoDBHost,ParameterValue=dynamodb.us-east-1.amazonaws.com ParameterKey=DynamoDBTable,ParameterValue=customer-vanity-numbers ParameterKey=VanityLimit,ParameterValue=5"

[dev.build.parameters]
no_beta_features = true

[dev.deploy.parameters]
stack_name = "ttec-react-stack-dev"
region = "us-east-1"
s3_bucket = "ttec-deployment-artifacts"
s3_prefix = "react-app-dev"
capabilities = "CAPABILITY_NAMED_IAM"
confirm_changeset = true